### PR TITLE
Fix package bundling (UMD)

### PR DESCRIPTION
**Pull request by omichelsen**
This PR adds standard UMD bundling fixing the following issues:

- Current AMD bundling is using wrong name for strophe (it’s now “strophe.js”), requiring you to alias the package to make it work.
- Moving “strophe.js” to peerDependency as having it as normal dependency will install a separate instance when using NPM. This means that the disco plugin get’s registered in the wrong instance and thus currently doesn’t work at all.

I have tested this new UMD bundle format on the following platforms:

- Webpack
- Node.js
- React Native
- Browser (no bundling, just <script>)

Using rollup removes the need to manually maintain the bundling, and will make it very easy in the future to output other formats as well as babel preprocessing should we want/need it.

### CODE REVIEW

**Comment by jcbrand** [comment]
This is great, thanks!

It doesn't look like you're including the rollup generated UMD file in the commit. I think it should also be included in the repo so that other projects don't need to perform a build step first. I'd also like to see what the generated UMD heading looks like.

**Comment by omichelsen** [comment]
It gets built as soon as it's published to NPM. Bower has been discontinued (and we have no `bower.json` anyway), so I don't see how anybody would consume it otherwise?

It's generally pretty bad standard to include build artifacts in your repo.

The heading looks like this:

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('strophe.js')) :
	typeof define === 'function' && define.amd ? define(['strophe.js'], factory) :
	(factory(global.window));
}(this, (function (strophe_js) { 'use strict';
```

All strophe references in the source gets updated so it works equally well with a global `window` object or the CJS `require` if you use a bundler.

I also have a question btw. Previously these plugins have been published under MIT, but now they have no clear license except for a few of them, that still contain a copyright header from ~2010. Can we agree on including an MIT license in all of them?

**Comment by jcbrand** [comment]
> It gets built as soon as it's published to NPM.

Ah ok, I didn't know that.

> Can we agree on including an MIT license in all of them?

The package.json does say that the license is MIT. Do you want to include the license file in the repo? That's probably a good idea because we need the original copyright header.

**Comment by sualko** [comment]
> It gets built as soon as it's published to NPM

That's an awesome idea to include the rollup script only in the package and not in the git repo. Thanks for your work.

**Comment by omichelsen** [comment]
@jcbrand the license prop in package.json is targeted NPM consumers. Github also recommends that you make [clear license attribution](https://help.github.com/articles/licensing-a-repository/) in the repo itself as a `LICENSE.txt` file.

I think we should have both, and remove it from the source files to avoid confusion/duplication. Also my company's legal department will be happy if we do this, so we follow standards from other open source projects :)

**Pull request merged**
